### PR TITLE
make the json path work for both direct messages and channel posts

### PR DESCRIPTION
**Pull request by xmcqueen**
per https://github.com/antirez/stonky/issues/4

the json struct seems to have changed between the direct message and a channel post

```
(36) bmcqueen-mn2:stonky.was bmcqueen$ cat chan_post.json | jq .result[0].channel_post.text
"$dldld"
(36) bmcqueen-mn2:stonky.was bmcqueen$ cat dm_post.json | jq .result[0].message.text
"$helpq"
(36) bmcqueen-mn2:stonky.was bmcqueen$ 
```

### CODE REVIEW

**Comment by antirez** [comment]
Hi @xmcqueen, thank you for the PR. When did this change happen? Right now I can use the bot both talking to it via direct messages and via channels without issues. Anyway the current PR introduces memory leaks, but in general I can't understand the problem very well since the current core is working correctly. Please could you explain the issue better? Thank you.

**Comment by xmcqueen** [comment]
I just noticed the problem yesterday, but that's also when I started to mess with stonky.  I'm wondering if they are rolling out an API change.  I'm in SF Bay area.

Here's a call to the API that shows two pending messages. I intentionally sent illegal messages, since i only wanted to verify delivery.

The first is a message which I sent to the bot via the bot's own private channel. That message is in the json at `.result[0].channel_post`.

The second message is a message which was sent to the general channel, of which the bot is an admin, and the bot is watching.  That message is in the json at `.result[1].message`.

I used curl and jq in the expected way: `curl -s 'https://api.telegram.org/botxxx/getUpdates?offset=-99&timeout=1&allowed_updates=message' | jq .`

```
curl -s 'https://api.telegram.org/botxxx/getUpdates?offset=-99&timeout=1&allowed_updates=message' | jq .
{
  "ok": true,
  "result": [
    {
      "update_id": 517926475,

      ### MESSAGE BLOCK IS RIGHT HERE ###
      "message": {
        "message_id": 38,
        "from": {
          "id": 222,
          "is_bot": false,
          "first_name": "xxx",
          "last_name": "xxx",
          "language_code": "en"
        },
        "chat": {
          "id": 222,
          "first_name": "xxx",
          "last_name": "xxx",
          "type": "private"
        },
        "date": 1614194721,

        ### MESSAGE 1 IS RIGHT HERE ###
        "text": "$$ msg direct to qbot"
      }
    },
    {
      "update_id": 517926476,

      ### MESSAGE BLOCK IS RIGHT HERE ###
      "channel_post": {
        "message_id": 75,
        "sender_chat": {
          "id": -1001233660747,
          "title": "Tchan",
          "username": "teachange",
          "type": "channel"
        },
        "chat": {
          "id": -1001233660747,
          "title": "Tchan",
          "username": "teachange",
          "type": "channel"
        },
        "date": 1614194763,

        ### MESSAGE 2 IS RIGHT HERE ###
        "text": "$$ message in tchan and qbot should see it and pick it up"
      }
    }
  ]
}
```

**Comment by xmcqueen** [comment]
I also pushed a fix for the memory leak.

**Comment by xmcqueen** [comment]
I'll try harder to figure out the usage to get it to behave per your expectations. It would be good to know why I'm seeing this difference.

**Comment by antirez** [comment]
That's super odd. I tested it again, same result. Well I think it is wise to support both the things... so that anyway the bot will be compatible whatever it receives. Thank you, I'll merge your PR and I may change a few things later in a successive commit. I'll update you here :)

**Comment by antirez** [comment]
Hello @xmcqueen, finally I fixed the problem, thank you. I used a different patch because it was possible to handle it in a much simpler way, like in f2cc9bd. Cheers.

**Pull request closed without merging**
